tdiary/tdiary-core

spec/fixtures/tdiary.conf.gem
spec/fixtures/tdiary.conf.rack
spec/fixtures/tdiary.conf.secure
spec/fixtures/tdiary.conf.webrick

spec/fixturesディレクトリ内のtdiary.confにて、@options['makerss.file']のパスに不要なpublicがついていたので直しました。`public/public/index.rdf` にフィードが出力される設定になっていました。
（テストでも使っていないので、特に実害はないのですが）

fix makerss.path (makerss.rb knows document root)

---

lib/tdiary/tasks/release.rake

パッケージ版のファイルサイズが50MB弱となっていて、その多くを同梱のgemが占めています。不要なファイルをパッケージから除くことで、ファイルサイズを削減します。
* `.bundle/ruby/*/cache/` に含まれるgemファイル
* 各gemの lib, data 以外のディレクトリ
これにより、ファイルサイズが基本セットで2MB, フルセットで6MB程度となります。
実際には、`gems/gemoji-2.1.0/images/emoji/unicode` と `gems/fastimage-1.6.6/test/fixtures`がサイズの大部分を占めるので、ここだけ狙い撃ちで消しても効果あると思います。gemojiライブラリは絵文字有無の判定だけで使っているようなので、imagesディレクトリは使っていません。

パッケージ版のファイルサイズを削減

---

lib/tdiary/application.rb
spec/core/application_spec.rb

#402 で指摘されたDos攻撃への対応です。TDiary::Application#callにて例外が発生した場合に、ステータスコード500を返します。
> あと、Dispatcherなどの層で例外が起きるとプロセスが落ちてしまうのはそういうものでしょうか。CGIの頃はそれでよかったと思うのですが、unicornなどでの運用だと潜在的なDoS攻撃リスクという意味でちょっと不安かなと思いました。具体的に他にまずいケースというのは思い付いてはないのですが。
もう一つの問題（不正な文字列への対応）もこのPRで合わせて対応します。
> 例外が起きているのはDispatcherでRackCGI.newしているところなので、RackCGI.newにブロックを渡してエンコーディング変換をする形が自然かなと思います。

DoS-resistant

---

lib/tdiary/application.rb
lib/tdiary/application/configuration.rb
lib/tdiary/cli.rb

assetsパスの読み込み方法の変更 (#375) によりbin/tdiaryのassets_copyコマンドが動かなくなっていました。
```
$ bundle exec bin/tdiary assets_copy
/Users/machu/work/tdiary/tdiary-core/lib/tdiary/cli.rb:63:in `assets_copy': undefined method `each' for nil:NilClass (NoMethodError)
from /Users/machu/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
from /Users/machu/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
from /Users/machu/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
from /Users/machu/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
from bin/tdiary:7:in `<main>'
```

fix broken assets_copy command

---

Gemfile
Gemfile.lock
lib/tdiary/cli.rb
lib/tdiary/tasks/release.rake

#397 の対応です。標準のRackサーバをwebrickにし、logオプションを追加しました。未指定時はこれまで通りに標準出力に表示します。

tdiary serverコマンドにlogオプションを追加

---

doc/HOWTO-authenticate-in-rack.md

callback urlを空にするとTwitter認証が動かない (#479) ため、ドキュメントに説明を追記しました。

add description about twitter callback url

---

ChangeLog
lib/tdiary/application/extensions/omniauth.rb

`Gemfile.local`にDalli gemがある場合に、セッションのストアを自動的に`Rack::Session::Dalli`にする。これでpumaやunicornを使った複数サーバを簡単に構築できるようになる。
他のストア候補がある場合には別解が必要だけど、編集用のセッションはそんなに永続的でなくてよいので、とりあえずmemcacheを使うのはアリかな、と。

use Rack::Session::Dalli automatically if dalli gem loaded

---

lib/tdiary/core_ext.rb

latest とmonth表示のときにActiveSupportの```SafeBuffer#html_safe```の中を通る際に、ブロック付き```gsub```の中で```$1```が消えてしまう問題があるので、そのworkaroundとして。
(AcriveSupportをどう直すかはまた別途……)

fix error in String#emojify on latest or month mode

---

ChangeLog
lib/tdiary/application/extensions/omniauth.rb

Twitter認証にしたとき、編集可能なユーザを複数指定したかったのでカンマ区切りでいけるようにしてみた。

enable to specify multiple twitter user in OmniAuth

---

config.ru

webrick環境でtDiaryが起動できなくなっています。
```
$ bundle exec rackup
/Users/machu/work/tdiary/tdiary-core/config.ru:2:in `require': cannot load such file -- tdiary/application (LoadError)
from /Users/machu/work/tdiary/tdiary-core/config.ru:2:in `block in <main>'
```
#483 で `File::expand_path` を使うように変更していますが、第1引数がすでに絶対パスだった場合に、 lib ディレクトリが join されないのが原因です。expand_pathのあとにjoinすることで、webrick, unicorn環境ともに起動できるようになりました。
unicornとpumaの環境で #483 の問題が起きていたのは、 `__FILE__` が相対パスか絶対パスかの違いだったのですね。
```ruby
__FILE__
=> 'config.ru'
File.join(File::expand_path(File::dirname( __FILE__ ), 'lib' ))
=> '/Users/machu/work/tdiary/tdiary-core/lib'
File.join(File::expand_path(File::dirname( __FILE__ )), 'lib' )
=> '/Users/machu/work/tdiary/tdiary-core/lib'
```
```ruby
__FILE__
=> '/Users/machu/work/tdiary/tdiary-core/config.ru' …
```

fix bug: doesn't start on webrick

---

ChangeLog
lib/tdiary/application.rb
lib/tdiary/version.rb

tDiaryの初回起動時に、以下の例外が発生して起動に失敗します。
```
(plugin/90migrate.rb):101:in `block in load_plugin': TDiary::ForceRedirect (TDiary::ForceRedirect)
from /Users/machu/work/tdiary/tdiary-core/lib/tdiary/plugin.rb:91:in `instance_eval'
from /Users/machu/work/tdiary/tdiary-core/lib/tdiary/plugin.rb:91:in `block in load_plugin'
from /Users/machu/work/tdiary/tdiary-core/lib/tdiary/plugin.rb:90:in `open'
from /Users/machu/work/tdiary/tdiary-core/lib/tdiary/plugin.rb:90:in `load_plugin'
from /Users/machu/work/tdiary/tdiary-core/lib/tdiary/plugin.rb:70:in `block in initialize'
from /Users/machu/work/tdiary/tdiary-core/lib/tdiary/plugin.rb:68:in `each'
from /Users/machu/work/tdiary/tdiary-core/lib/tdiary/plugin.rb:68:in `initialize'
from /Users/machu/work/tdiary/tdiary-core/lib/tdiary/application.rb:83:in …
```

catch TDiary::ForceRedirect exception from 90migrate.rb at startup

---

Gemfile.lock

bundle install fails as follows:
```
% bundle install --path vendor/bundle --jobs=4 --frozen 
Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Could not find term-ansicolor-1.3.1 in any of the sources
```
term-ansicolor 1.3.1 is yanked.

bundle update (term-ansicolor 1.3.1 is yanked)

---

Gemfile.lock

bundle install fails as follows:
```
% bundle install --path vendor/bundle --jobs=4 --frozen
You are trying to install in deployment mode after changing
your Gemfile. Run `bundle install` elsewhere and add the
updated Gemfile.lock to version control.
If this is a development machine, remove the Gemfile freeze 
by running `bundle install --no-deployment`.
You have deleted from the Gemfile:
* pry
% git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
% bundle config --delete frozen
% bundle install --path vendor/bundle --jobs=4         
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving …
```

bundle update (libv8 3.16.14.9 is yanked)

---

lib/tdiary/core_ext.rb
spec/core/core_ext_spec.rb

* ツッコミで絵文字「thumbsup」を使う
* Emojiライブラリが「thumbsup」のaliasとして「+1」を返す
* 「+」がエスケープされていないので正しいURLにならず、404
HTML展開のテンプレートでCGI.escapeをするように修正。外部入力をそのまま使うわけではないので、セキュリティ要素はありません。

fix invalid HTML when use 'thumbsup' emoji in comment

---

lib/tdiary/configuration.rb

ソースを読んでいて、Configure#configure_attrsで未初期化の変数bをevalに与えているのが気になりました。

explicitly eval tdiary.conf without binding

---

lib/tdiary/filter/spam.rb
misc/plugin/amazon/amazonimg.rb
misc/plugin/ping.rb
misc/plugin/recent_rss.rb
misc/plugin/weather.rb

Ruby 2.3.0 から以下の警告が出るようになったので ```Timeout.timeout``` を明示して使うようにします
```sh
tdiary-core/lib/tdiary/filter/spam.rb:168:in `lookup': Object#timeout is deprecated, use Timeout.timeout instead.
```

Use Timeout.timeout instead of Object#timeout

---

js/amazon.js
js/amazon_bitly.js
lib/tdiary/configuration.rb
lib/tdiary/core_ext.rb
lib/tdiary/plugin/00default.rb
misc/plugin/amazon.rb
misc/plugin/image.rb
spec/plugin/plugin_helper.rb

#506 での携帯電話に続き、スマートフォンで特別なページ生成をやめ、ブラウザサイドで対応する。
* metaタグで常にviewportを指定
* Configuration#smartphone? メソッドで常にfalseを返す
* smartphone?によって場合分けしている部分の削除
jsではスクリーンの幅が360未満の場合にスマートフォン扱いするコードにした(amazon.js)

サーバサイドでスマートフォン用のページ生成をやめる

---

lib/tdiary/filter/spam.rb
misc/plugin/recent_rss.rb
misc/plugin/weather.rb
spec/acceptance/save_conf_dnsbl_spec.rb

2.3.0 で warning が出るようになった `TimeoutError` がまだ残っていたので `Timeout::Error` に置き換えてしまいました。

use Timeout::Error instead of TimeoutError

---

misc/plugin/category.rb

tDiaryを3から4へバージョンアップしたら <%=category_list%> で表示されるカテゴリ一覧がソートされなくなりました。ここはソートされている方が使いやすいと思います。
category.rbでは <%=category_dropdown_list%> で表示されるドロップダウンリストや編集画面でのカテゴリ一覧を作る各メソッド内で @categories をソートするようになっていましたが、それなら @categories に代入する際にソートしたらいいと思ったので、そのようなパッチを作ってみました。
こうすると <%=category_list%> で表示されるカテゴリ一覧もソートされるようになるのですがいかがでしょうか。

カテゴリ一覧はソートされていて欲しい

---

Gemfile
Gemfile.lock
lib/tdiary/core_ext.rb
spec/core/core_ext_spec.rb

gemoji の ruby code 部分は MIT/X11 License なのですが，同梱されている画
像が non-free です．tDiary 本体での gemoji の利用は絵文字の画像そのもの
を利用せずに http://www.emoji-cheat-sheet.com/ の URL 参照に変更している
だけかと思います．
画像を同梱しないライブラリへの依存に変更しては如何でしょうか．例えば，と
いうことで https://github.com/melborne/emot を利用する修正を書いてみまし
た．
The "gemoji" has some license issues, e.g.:
http://words.steveklabnik.com/emoji-licensing
Clearly, this library is not  compatible GPL-2.0+.
This commit replace dependency: gemoji to emot. This library is under
MIT/X11 license and does not contained non-free images.
Signed-off-by: Youhei SASAKI <uwabami@gfd-dennou.org>

Replace dependency: gemoji to emot

---

.travis.yml
ChangeLog
Gemfile
Gemfile.lock
lib/tdiary/cli.rb
lib/tdiary/environment.rb
lib/tdiary/version.rb
misc/templates/Gemfile.erb
misc/templates/Gemfile.local.erb
tdiary.gemspec

PR #515 のコミットを整理しました。
> tdiary/tdiary-contrib#121 と同じようにcore側もgem周りを改善しました。
> 
> * gitがない環境でも.gemspecを読み込めるようにしました
> * tdiary-coreの必須ライブラリはGemfileではなくtdiary.gemspecに記載しました
> 
> tdiary-coreの依存ライブラリを.gemspecに書くようにすれば、gemでインストールしたtdiaryのアップデートが楽になります。今まではgemの更新後にtdiaryインストールディレクトリのGemfileを手動で書き換える必要がありました。

tdiaryの依存ライブラリをGemfileではなくgemspecに記述する

---

ChangeLog
lib/tdiary/rack/auth/omniauth.rb

#494 で報告のあったTwitterやFacebookの認証を使う場合に、セッション情報を `Rack::Session::Pool` に格納すると認証に失敗する問題を修正しました。
原因は、リクエストのたびに `TDiary::Rack::Session` を作るコードになっていたことです。`Rack::Session::Pool`は自身のオブジェクト内にセッション情報を持つので、リクエストのたびにオブジェクトが作られることでセッション情報が破棄されてしまっていました。

fix authentication error by omniauth and rack::session::pool

---

.travis.yml
ChangeLog
Gemfile
Gemfile.lock
lib/tdiary/cli.rb
lib/tdiary/environment.rb
lib/tdiary/version.rb
misc/templates/Gemfile.erb
tdiary.gemspec

Herokuでbuildできない問題 (#527) を解決するために、 61b7b6c520e69a09d717b089fbfb8f012e2b7ed8 のコミットをrevertしました。

Revert "move essential gems from Gemfile to .gemspec"

---

ChangeLog
lib/tdiary/application.rb

tdiary.confで@indexや@updateがURLだった場合にrouteが見つからずにエラーになるので修正。
@machu どうですか?

fix error when @index or @update specified with URL in tdiary.conf

---

lib/tdiary/plugin/00default.rb
misc/plugin/calendar2.rb

変更点
* DOCTYPEの書き換え
* meta要素でのcharsetの指定方法を変更
* Content-Script-TypeとContent-Stype-Type指定は不要
* scriptおよびlink要素のtype属性を省略
* table要素のsummary属性はobsolete
* meta要素でのlast-modified指定は無効

support HTML5

---

lib/tdiary/core_ext.rb

日記のURLはhttpsだけど、reverse proxyからtDiaryまではhttpで来てるような環境(Herokuとか)にはENV['HTTPS']が入っていないので、ENV['HTTP_X_FORWARDED_PROTO']も見るようにした。

support forwarded HTTPS

---

ChangeLog
lib/tdiary/version.rb
misc/plugin/title_tag.rb

title_tagプラグインの中でcategoryプラグインの存在確認をしている箇所があったので、category-lite(を含むカテゴリプラグイン仲間)を検出するように条件を緩和。

support category-lite plugin in title_tag plugin

---

misc/plugin/theme_online.rb

theme_onlineプラグインで使うデフォルトのURLをgithub pages上にあるテーマにすることで、httpsでのアクセスにも対応する

use online themes on github pages for accessible by https

---

ChangeLog
misc/paas/heroku/config.ru

Heroku用の不要なconfig.ruを削除してデフォルトのものを使うように変更

delete config.ru for Heroku (use default one)

---

js/image.js

imageプラグインの image.js の中で、廃止された`` .live`` 関数が使用されており、これがエラーになっていて後続の JavaScript が実行されずにおりましたので、``.on`` に変更しました。
(編集画面 picasa.js が動いていなかったので気付きました。picasa.js は修正不要でした :sweat_smile:)
この修正でよろしいでしょうか。ご覧ください。

Fix image plugin for jQuery 2.x

---

lib/tdiary/application.rb
lib/tdiary/cli.rb

gem の tdiary assets_copy コマンドが
```
(略)/tdiary-4.2.1.20160108/lib/tdiary/cli.rb:63:in `assets_copy': undefined method `config' for TDiary::Application:Class (NoMethodError)
```
というエラーで動かなかったので修正しました。
修正方法がこれで正しいか自信がないので、ご教示いただければ幸いです。

fix the assets_copy command in cli

---

ChangeLog
misc/plugin/title_tag.rb

title_tagプラグインで、日タイトルやサブタイトルがない場合には日記名のみを<title>要素に設定するように修正

print only diary name when diary has no subtitles

---

lib/tdiary/plugin/00default.rb

CSSのロードを(プラグインを入れていればたくさんになる) JavaScript ファイルの前にする PR です。
- iOS 9.2.1 で、大量のjsの後にCSSを読むようにしていると異様にCSSロードが遅い
- そもそも[CSSを先に読み込んだ方がブラウザにとってパフォーマンスがよいらしい](http://stackoverflow.com/questions/4198624/order-of-loading-external-css-and-javascript-files)
という理由から、CSSのロードを先にした次第です。
もし問題がなければ採用していただければ天にも昇るロード心地が致します。

change order loading CSS and JS

---

.travis.yml
ChangeLog
misc/plugin/category.rb
misc/plugin/category_legacy.rb
misc/plugin/en/category.rb
misc/plugin/en/category_legacy.rb
misc/plugin/ja/category.rb
misc/plugin/ja/category_legacy.rb
spec/acceptance/view_category_spec.rb

仕様をシンプルにして軽量化したあたらしいcategoryプラグイン(contrib収録のcategory-liteプラグイン)で、categoryプラグインを置き換える。旧categoryはその構造に依存したプラグインが存在するため、category_legacyとして残す。

replace category plugin by contrib/category-lite plugin. fix #528

---

ChangeLog
misc/paas/heroku/tdiary.conf

HerokuのmLab addonが設定するMongoDBのURIが、環境変数「MONGOLAB_URI」から「MONGODB_URI」に変更になったので、MONGODB_URIを優先して使うように変更。互換性維持のために引き続き「MONGOLAB_URI」も参照している。

use MONGODB_URI environment variable instead of MONGOLAB_URI

---

benchmark/benchmark_io_default.rb
lib/tdiary/io/default.rb

呼び出される回数が多い `Default::IO#calendar` を速くしました。
```
% ruby benchmark_io_default.rb
Warming up --------------------------------------
calendar    16.000  i/100ms
calendar2    22.000  i/100ms
Calculating -------------------------------------
calendar    195.073  (±14.9%) i/s -    960.000  in   5.070197s
calendar2    237.695  (±13.9%) i/s -      1.166k in   5.039136s
```
おおよそ、10-15% 速くなっています。

Performance Improvement of `Default::IO#calendar`

---

Gemfile
lib/tdiary/environment.rb
lib/tdiary/tasks/release.rake

tDiaryのパッケージ版からsproketsライブラリを取り除く提案です。
cygwin+CGI環境でtdiary5.0.0が起動しない問題 (#569) で、CGI環境では使わないsprockets関連の読み込みに失敗しているので、パッケージ版はなるべく依存関係をなくして配布したほうが良いと思いました。
副作用として、rack環境ではパッケージ版を使えなくなります。いちおう[公式ドキュメント](https://github.com/tdiary/tdiary-core/blob/master/doc/INSTALL-rack.md)には、rack環境ではtdiary gemを使うようにしているので影響ないと思いますが。

remove sprockets from release package

---

lib/tdiary/application.rb
lib/tdiary/extensions.rb

tdiary-coreとtdiary-blogkitの組み合わせで、core側のassetが見えなくなる問題を修正しました。`tdiary/extensions/core` を明示的に呼び出すようにしています。
* see: tdiary/tdiary-blogkit#8

Cannot use core assets when TDiary::Extension was already declared

---

Gemfile
Gemfile.lock
lib/tdiary/tasks/release.rake

tdiary.orgの移設に向けて、パッケージの保存先を www.tdiary.org から [github releases](https://github.com/tdiary/tdiary-core/releases) に変更します。
* usage: `$ GITHUB_ACCESS_TOKEN={your_token} bundle exec rake package:release`
* see: https://help.github.com/articles/creating-an-access-token-for-command-line-use/

change package:release destination from tdiary.org to github.com

---

misc/plugin/amazon.rb

Fixed https://github.com/tdiary/tdiary-core/issues/579
以前の実装では item をまず node として取り出してから item が空の時に別の node として保存されているエラーメッセージを取り出していましたが、`AmazonItem`に統合した時の対応漏れで #579 のようなエラーを出していました。
以前と同等の処理となるように `AmazonItem`の中で item が取れているかどうかを判定し、失敗している場合は改めて node を参照して取り出すような処理に変えました。
@tdtds 以前の実装と、こう変えたという部分のコードを見てもらってよいでしょうか。

Fixed nil references when item metadata could not fetch from amazon api

---

ChangeLog
lib/tdiary/version.rb
theme/base.css
theme/default/default.css

flickrプラグインが他の画像系プラグインと異なり、同一要素に`img.left` / `img.right`と`img.photo`の両方のクラスを指定するが、`img.photo`の方があとに定義されているテーマだと画像が左寄せ/右寄せされない。
flickrプラグインの挙動は間違っていない(むしろ好ましい)ので、`img.photo`の定義を`img.left` / `img.right`よりも前にした。

define img.right and img.left after img.photo

---

lib/tdiary/cli.rb
lib/tdiary/dispatcher.rb
lib/tdiary/server.rb
lib/tdiary/style/wiki.rb
spec/plugin/bq_spec.rb

`synvert -rruby/new_hash_syntax` を使って `{:foo => :bar}` を `{foo: :bar}` に置換しました。
単なる style change なので CI 通過後にマージします

Ruby 1.9 以降で使える Hash syntax に揃える

---

lib/tdiary/plugin/00default.rb

[The result of Open Graph Object debugger](https://developers.facebook.com/tools/debug/og/object/?q=https%3A%2F%2Fsatoryu-diary.herokuapp.com%2F) says that `og:description` should be specified for the top page of a tDiary. 
The ogp headers are provided by the default plugin: `lib/tdiary/plugin/00default.rb` without ogp plugin packed in tdiary/tdiary-conrib. 
The scope of this PR is to fix the default plugin so that the warning messages go.

OGP headers provided by default plugin lacks some properties. 

---

lib/tdiary/environment.rb
tdiary.gemspec

tdiaryをgem経由で使うときに、いまだとtDiaryの依存ライブラリを外部のGemfileにも書かなければいけません。tdiary.gemspecにも依存ライブラリを書いておくことで、外部のGemfileではgem 'tdiary'`とだけ書けば良くなります。
たとえば、 tdiary/tdiary-io-mongodbに付属のtdiary-mongodb-convertを動かすときや、tdiary/tdiary-orgのようにtDiaryを`gem 'tdiary'`として読み込んで使う時に、emotなどの依存ライブラリをGemfileに書かなくて良くなるのが嬉しいです
本当はtdiary-coreをgitで取得してそのまま動かす場合もtdiary.gemspecを使うようにしたいのですが、Herokuで動かない問題 (#527) があるので今はこのままです。

tDiaryの依存ライブラリをtdiary.gemspecに記述する

---

ChangeLog
lib/tdiary/version.rb
misc/plugin/category-legacy.rb
misc/plugin/category.rb

ヒアドキュメントの終端文字列と同じ文字列を日記に書き込むことでエラーになるという報告を受けての修正。 see http://tdiary-users.osdn.jp/cgi-bin/wforum/wforum.cgi?mode=allread&no=6793&page=0
* ヒアドキュメントの代わりにString#dumpを利用
* 一部のコードをループの外に出した(最適化)

fix error about here document in category plugins

---

index.fcgi
update.fcgi

h2o のような apache2 以外の http サーバーで fcgi を動かすときに apache2 に依存した環境変数で落ちる箇所を直しました。
具体的には `ENV['SCRIPT_FILENAME']` が h2o では設定されないので、雑に自分自身のパスを渡して、同じディレクトリにある index.rb/update.rb をロードするようにしています。

Added default value for script filename for fcgi endpoint

---

misc/plugin/amazon.rb

AmazonプラグインでHTML5非準拠の記述があったので直しました。
本来はCSSに置き換えるのが正しいようですが、そのまま削除しても問題なさそうです。
（外側の`span.amazon-detail`が`display: block`なので）

amazon.rb: The clear attribute on the br element is obsolete.

---

misc/plugin/xmlrpc/xmlrpc.rb

#600 派生。xmlrpcライブラリはruby 1.8以降は標準添付なので、入手方法の記述は不要。

delete description of xml-rpc library from xmlrpc plugin

---

misc/plugin/amp.rb

tDiaryをgemでインストールした場合に、AMPプラグインが動かない問題を修正しました。

amp.rb: fix bug, plugin does not work in gem mode

---

lib/tdiary/filter/spam.rb
lib/tdiary/plugin/10spamfilter.rb

ローカル環境のtDiaryが遅い（応答に5秒以上かかる）現象があり、調べるとspam-champuruへの問い合わせがタイムアウトになる5秒間待機していました。
#276 でspam-champuruのサービス終了へ対応していますが、SPAMフィルタの設定画面を開かないとマイグレーションが有効にならないため、古い設定が残ったままでした。
対策として、以下を修正しました。
* 常にDNSマイグレーションを実行する
* DNS問い合わせのタイムアウト時間を5秒から1秒に短縮

spam-champuruへの問い合わせでtDiaryが遅くなる問題を修正

---

misc/plugin/amp.rb

amp.rb プラグインで amphtml がおかしい問題 #613 を修正していました。
レビューをお願い申し上げます。
`spec/plugin/amp_spec.rb` は書き方がよくわからなかったのでつけませんでした。すみません。

fix amphtml URL for '?date=YYYYMMDD' style diary

---

ChangeLog
lib/tdiary/configuration.rb
lib/tdiary/plugin/00default.rb
lib/tdiary/version.rb

`tdiary.conf`読み込み時に、テーマの場所(現在は`local`か`online`)の情報を`@theme`に確実に入れる。プラグインはこの情報が`@theme`に含まれることを期待して良い。

insert theme location (local or online) into @theme in tdiary.conf

---

misc/paas/heroku/Gemfile.local
misc/paas/heroku/Gemfile.lock

mongo gemがruby 2.4.0で動かないので、Heroku向けのGemfile.localでruby 2.4を指定するのをいったんやめる。ruby 2.4.1では修正されているので、それを待って戻す。

revert to support ruby 2.4 to 2.3 on Heroku

---

ChangeLog
lib/tdiary/plugin/00default.rb
lib/tdiary/version.rb

#616 でエンバグした @css が有効にならない問題を修正

fix ignore @css by theme location in tdiary.conf

---

.travis.yml
Gemfile

最近のRubyでもpry-byebugが動くようにしました。

enable pry-byebug at MRI 2.1 or higher

---

lib/tdiary/io/default.rb

古い日記データを以降しようとすると、tdrファイルの解析でこけます。
見ると、ruby1.9以降廃止されたStringへのeachを使っていたので、修正してみました。

古いtdrファイルを最近のrubyで復旧できるよう修正

---

lib/tdiary/plugin/00default.rb

contrib の ogp.rb プラグイン使用時に、どうも `default_ogp` メソッドによって og:image メタタグが2つ生成されてしまうのを修正しようとしています。(1つ目は `default_ogp` メソッドが `<meta content="diary-url/images/ogimage.png" property="og:image">` のようなタグを、そして2つ目に ogp.rb プラグインが本来の og:image タグを生成していて、前者は not found となりfacebookなどでURLを貼ったときに真っ白けになっています。)
元は、`@conf.banner` が `defined?` かどうかをチェックしていたり `.nil?` したりしているのですが、
1. まず https://github.com/tdiary/tdiary-core/blob/master/lib%2Ftdiary%2Fplugin%2F00default.rb#L327 は否定なのではないか? (そうでしょうか?)
2. さらに、`@conf.banner` が `''` だったりすることもあり、`nil` チェックだけではだめなのではないか?
と考えて、ひとまずこのコード変更をしてみています。
ogp.rb プラグインをお使いの方、特にレビューをお願いしたく存じます。

fix multiple og:image meta tags

---

ChangeLog
lib/tdiary/version.rb
misc/plugin/amp.rb

ampプラグインを有効にした状態で存在しない日の日記を表示するとエラーになります。以下のように修正します:
* 通常表示時にはエラーを無視
* plugin=amp指定時には404を返す

fix error of amp plugin on the day is empty

---

misc/plugin/amazon.rb

rpaproxy が `Errno::ECONNREFUSED` を返した時に日記がエラーで表示できなくなってしまうので最低限のハンドリングを入れました。なお、これでも `preview` の時はエラーになります...(あとで)

Handle Errno::*

---

lib/tdiary/dispatcher/index_main.rb
lib/tdiary/dispatcher/update_main.rb

全面的にUTF-8へ移行したのにContent-Typeで明示的にcharsetを返していなかったので、返すようにしました。index.rbとupdate.rbの正常系2ヶ所のみ。エラー処理などのところには入れていません。

return charset as 'UTF-8' by Content-Type

---

lib/tdiary/application.rb
lib/tdiary/rack.rb

7e9debe691045835b7534224a0249c3cfc2754cf で削除済みだった sprockets を利用して CoffeeScript をトランスパイルする rack middleware への参照が残っていたので削除しました。
これ、明らかに `autoload` でエラーが出ると思うんですが誰も使ってないことがバレてしまった...

Removed obsoleted rack middleware about coffeescripts.

---

lib/tdiary/environment.rb

Bundlerを1.15から1.16 pre2にあげたら非互換で動かないところがあったので、1.15 / 1.16両対応をしてみた
* 従来使っていた`Bundler::Settings#without`は1.16から消えているので代わりに`#[:without]`を使う
* `Bundler::Settings#[]`は1.15で`nil`を返すことがあるのでその場合は`[]`を使う(1.16は空配列を返す)

fix incompatibirity between bundler 1.15 and 1.16

---

.vscode/launch.json
Gemfile
Gemfile.lock

Visual Studio CodeエディタでtDiaryをデバッグできるように、デバッグ用のgemと起動用の設定を追加します。
see. https://code.visualstudio.com/docs/editor/debugging

enable debugging in Visual Studio Code

---

.travis.yml

TravisCIで使うrubyのバージョンをそれぞれ最新にし、2.5.0を追加。

update ruby versions on TravisCI

---

ChangeLog
lib/tdiary/io/default.rb
misc/plugin/category-legacy.rb
misc/plugin/category.rb
misc/plugin/recent_comment3.rb
misc/plugin/recent_list.rb

maybe fix #654 and tdiary/tdiary-blogkit#17
ようするに内部で`DiaryContainer`クラスを使おうとすると`autoload`が走ってセキュリティエラーになる、ということなので、とりあえず明示的に`require`するようにした。

fix #654: insecure errors in some plugins using DiaryContainer

---

misc/plugin/amp.rb
spec/plugin/amp_spec.rb

img要素のパラメタが「>」を含んでいる場合、amp-img要素への変換が失敗するので修正。本来は「>」は日記記述者がエスケープすべきだが、いちおうこれでフォローできる。

fix converting img to amp-img tags when parametes have '>' chars

---

misc/paas/heroku/tdiary.conf
misc/plugin/dropdown_calendar.rb
spec/fixtures/tdiary.conf.gem
spec/fixtures/tdiary.conf.rack
spec/fixtures/tdiary.conf.webrick
tdiary.conf.beginner

dropdown_calendarが生成するURLは長らくanchor()が生成するそれと異なっていたが、これを合わせるために以下の変更を行った。
* inline JavaScriptを使って、リストから選択するだけでanchor()が生成したURLに直接ジャンプする
* 指定したラベルはリストの最上部に挿入(↑の実装のため最上部のアイテムが選択できない故)

improve dropdown_calendar plugin

---

misc/plugin/amazon.rb

amazon auth proxyがエラーを返してきたときなどに`Net::HTTPExceptions`が発生するのを捕まえていなかったため、日記がエラーメッセージのみになる場合があった。この修正でエラーそのものは解消されないが、amazon.rbの出力はASINのみになって他の文章に影響はなくなる。

amazon.rb: catch Net::HTTPExceptions and log the reason

---

.dockerignore
Dockerfile
lib/tdiary/cli.rb
lib/tdiary/rack/auth.rb

Dockerfileを改善して実用性を高める。
* ベースをruby:2.5に変更
* 環境変数`HTPASSWD`がある場合はそのファイルを使ってBASIC認証する
* Dockerfile内でENVに`HTPASSWD`として`data/.htpasswd`を指定
* .dockerignoreに`.htpasswd`を追加
* Dockerfile内でGemfile.localを生成してcontribおよびstyle-gfm、style-rd、puma gemを追加

Improve Dockerfile

---

lib/tdiary/tasks/release.rake

BSD版tar (MacOS)で作られたパッケージをGNU版tarで展開するときにwarningが出る問題をなくす。 see comments of #698

fix #698 warning in tarball  made by macos

---

misc/plugin/amazon.rb

Amazon書影のデフォルト画像がhttpで配布されていたので、tdiary.github.io上に展開してそちらを指すように変更。

fix #751: replace amazon default images in tdiary.github.io

---

Gemfile
Gemfile.lock
lib/tdiary/application.rb
lib/tdiary/rack/static.rb
misc/paas/heroku/Gemfile.lock
spec/core/rack/static_spec.rb
tdiary.gemspec

遥か昔に CoffeeScript や sass などを自動でコンパイルして、rack で透過的に扱えれば便利だろうと入れた sprockets ですが時はたち、babel で transpile して、webpack などで bundle したものを配布する世の中になってしまいました。
tDiary でも実際には `rake assets:copy` タスクなどで `public/assets` にまるっとコピーして tar.gz を配布しているのであまり活用されていません。というわけで依存関係から消してしまおうと思います。
`assets:copy` をよっしゃここで webpack だ〜と行ければ良かったのですが、今の javascript/css だと一気にジャンプするのは無理そうでした。それは次のフェーズでやります。
TODO: 配布パッケージなどの先までもう少し精査していきます。

Remove sprockets, assets pipeline is obsoleted in 2018

---

.travis.yml
lib/tdiary/tasks/release.rake

stop support ruby 2.3.x

---

lib/tdiary/application.rb

* degraged by #674
* use tDiary#assets_paths for static paths

support extentions (cf.tdiary-contrib) assets paths again

---

.travis.yml
package.json

jQueryのアップデート(3.4.1)にともない、Travisでjasmine:ciがエラーになるようになったので、Travis上でのみPhantomJSをダウングレードしていた指定を削除した。また同時にjasmine-jqueryを最新版へ。

update PhantomJS for TravisCI

---

Dockerfile

外部から環境変数PORTで使用するポートを指定してくるクラウドサービス(Google Cloud Runなど)を想定して、Dockerfile内で環境変数を使うように修正。環境変数を展開するためにCMDをシェル形式に変更した。

use PORT environment in docker image

---

misc/plugin/amazon.rb

amazonプラグインにて
```
undefined method `has_item?' for nil:NilClass (NoMethodError)
(plugin/amazon.rb):305:in `rescue in amazon_get'
(plugin/amazon.rb):279:in `amazon_get'
(plugin/amazon.rb):387:in `isbn_image'
```
というエラーが出るため調べたところ、XMLであるはずのキャッシュが `true` という文字列のみになっていました。
HTTP Redirection 以外に HTTP Found でもリダイレクトしていたためそれを追加、また既に間違って `true` をキャッシュしていた場合は取得し直すようにしました。

amazon plugin: support HTTP Found response and discard wrong stored cache

---

misc/plugin/makerss.rb

9b989a296c12db9c69131840603c6b231ded848c のコミットを見ると mobile link discovery に対応するための処理は取り除かれたのだと思いますが、makerss.rb 内には処理が残っていたのでそれを削除するパッチを作りました。
https://sourceforge.net/p/tdiary/code/2612/ で行われた修正を取り消す形になりますがいかがでしょうか。

makerss.rbから mobile link discovery 用の出力を削除

---

misc/plugin/makerss.rb
spec/plugin/makerss_spec.rb
spec/plugin/plugin_helper.rb

makerss.rb が出力するXMLには、CSSを適用するための次の行が必ず出力されています。
```
<?xml-stylesheet href="rss.css" type="text/css"?>
```
しかし、RSSにCSSを適用したいケースはあまりない気がします。なので、この行を出力しない設定ができるといいなと思いました。
上記の行を出力しないようにすると、次の些細なメリットがあります。
* rss.cssを取得するHTTP要求が来なくなる。
* index.rdfをウェブブラウザで開いたときにXMLとしてレンダリングされるようになる（このためには #812 の変更も必要）。今のindex.rdfは、各タグの内容だけがレンダリングされてしまうようです。
本PRでは、 `makerss.use_stylesheet` というオプションを追加し、そこに false を設定すれば上記の行が出力されないようにする変更を行っています。互換性を維持するため、このオプションが未設定の場合は今まで通り上記の行を出力するようにしています。
また、 spec/plugin/amp_spec.rb を真似してテストも追加してみました。

makerss.rb: remove xml-stylesheet

---

Dockerfile

bundler 2.0.2が必要だったのでDockerfile内で`gem install bundler`するようにした。

update Dockerfile for ruby to 2.6.5

---

ChangeLog
lib/tdiary/comment_manager.rb
lib/tdiary/version.rb

いくつかの`IO`が時系列をバラバラにしてツッコミを追加することがあるので、受け取った側で毎回ソートするようにした。
前もってソートすることを`IO`実装時のルールとしても良いが、修正箇所が少ないこちらを採用したい。
欠点として、多数のツッコミを読み込むときに無駄なソート処理がたくさん走るので、性能劣化がある(が無視して良いと考える)。

sort comments by date on a new comment added

---

ChangeLog
lib/aws/pa_api.rb
lib/aws/sig_v4.rb
lib/tdiary/version.rb
misc/plugin/amazon.rb

Amazon PA-APIのv5への移行期限が11月末までに迫っているので実装。
* lib/awsの下に関連ライブラリを実装した
* amazon.rbのインタフェースはできるだけ変えない
* 認証proxyは廃止の方向で(API利用に制限がありすぎて開放する意味がなくなっている)

support Amazon plugin on PA-API v5

---

misc/plugin/amazon.rb

amazonプラグインにて、PA-APIが返してくるJSONをパースしていなかった。キャッシュから読んだときだけパースしていたので、2回目以降の呼び出しにて正常に動作する(つまりリロードすると直るので気づかなかった)。
Herokuのようなキャッシュが長期間持続しない環境で発生しやすい。

correct parsing json in amazon plugin

---

lib/tdiary/plugin/00default.rb

favicon・サイトアイコンはそろそろSVGもかなりのブラウザで使えるようになっているのでSVGを指定したときに  `type="image/svg+xml"` を付けるようにしてみました。
- https://caniuse.com/#search=svg%20favicon

add svg icon image type

---

lib/tdiary/plugin/03purge_cache.rb

* the purpose is making a trigger of purge caches on CDN
* some plugin can appen procs by using add_purge_cache_proc
* the proc receives an array of pages to be purge
Signed-off-by: Tada, Tadashi <t@tdtds.jp>

purge cache plugin into default

---

js/category.js
misc/plugin/category-legacy.rb
misc/plugin/en/category-legacy.rb
misc/plugin/ja/category-legacy.rb

バージョン5.1.1から、プラグインのcategory-legacy.rbを使用している場合にカテゴリ別表示の画面が正しく表示されなくなっているようです。
category-legacy.rbではカテゴリ別表示の画面にて全カテゴリの記事一覧を同時に表示することができますが、そうした場合に各カテゴリに全カテゴリ分の記事一覧が表示されてしまいます。
* カテゴリA
* 記事タイトル1
* 記事タイトル2
* カテゴリB
* 記事タイトル3
* 記事タイトル4
と表示されるべきときに
* カテゴリA
* 記事タイトル1
* 記事タイトル2
* 記事タイトル3
* 記事タイトル4
* カテゴリB
* 記事タイトル1
* 記事タイトル2
* 記事タイトル3
* 記事タイトル4
のように表示されてしまいます。
#866 でcategory.jsに逆順表示処理が追加されたのが原因のようなので、category-legacy.rb使用時でも動くようにするpull requestを作成しました。

category-legacy.rb使用時に全カテゴリ表示が正しく表示されない

---

misc/plugin/calendar2.rb

calendar2プラグインで「前N日分」「次N日分」表示のとき、適切なカレンダーが表示されず、また存在する日記へのリンクが生成されない問題を修正。表示する月は以下の日付をベースにする (上から順にトライする):
1. `@date`があればその日付
2. `@diaries` に含まれる最古の日付
3. 現在時刻
副次効果として、長期間更新されていない日記で最新の日記に合わせたカレンダーが表示されるようになる。
だいたいの場合これで大丈夫だが、例外的におかしなカレンダーが表示される場合もある(たとえばN年日記モード)が、そもそも単一の月カレンダーで表現できないページなのであきらめる。

calendar2 plugin: fix wrong calendar in next/prev diaries mode

---

lib/tdiary/rack/auth/omniauth.rb

OmniAuth2をとりあえずサポートする。
一時的に `OmniAuth.config.allowed_request_methods` へ `:get` を指定することで従来の動作(GETメソッドによる認可処理)を指定している。ただしこれはCSRFのリスクがあるので推奨されない。最終的にはPOSTを使うようにすべきである。

suppurt OmniAuth2

---

README.md

[tDiary-5.1.5 リリースノート](https://tdiary.org/20210228.html)でCI環境がGitHub Actionsへ移行されたことを知り、Travisはもう使われていないようなので、プロジェクトのビルドステータスを表すバッジとリンク先もGitHub ActionsのURLに変更しました。
生成されるバッジ画像の見た目は[.github/workflows/ci.yml](https://github.com/tdiary/tdiary-core/blob/master/.github/workflows/ci.yml)の `name` が参照されるため、「ubuntu」が表示されます。

Change build status URLs to GitHub Actions

---

lib/tdiary/tasks/release.rake

Because Ruby 2.6+ bundled bundler as the default gems.
Fixes https://github.com/tdiary/tdiary-core/issues/884

Removed vendored bundler files 

---

misc/plugin/amazon.rb

Amazon での売り上げが一定期間ない時に Amazon PA API は `429 "Too Many Requests"` を返し続けるようで、その時にひたすら ASIN が文字列でだけ表示されても日記としては読者の役に立たないのですごく雑にリンクを作るようにしました。
これにアソシエイトタグをつけた方がいいのかどうしたもんでしょうか。

Handle and print raw URL when amazon returned 429 error

---

ChangeLog
lib/tdiary/lang/ja.rb

キーワード引数の非互換で、メールへのエンコード処理がエラーになっていた。`String#encode` のパラメタをHashではなくキーワード引数に修正。

fix #967 error in `String#encode` cause by keyword parameter incompatible

---

ChangeLog
lib/tdiary/cli.rb

vscodeのデバッグで `tdiary server` コマンドが動かなかったのを修正。
`require 'webrick'`がサイレントで死ぬのだが(謎)、`if` の外に移動してみたら動いたので、とりあえずこれで。

fix debugging on vscode

---

misc/plugin/amazon.rb

`{{isbn '0000000000', 'hoge'}}` のような使い方をしていて `429` が返ってきた際に、label を含むリンクを作るようにしました。

amazon.rb :  429 Too Many Requests が返ってきたときのリンクに label を使用する

---

js/image.js

imageプラグイン使用時、日記の更新画面で次の操作をしたときにimageプラグイン呼び出しの記述（Wikiスタイルだと `{{image 0, '画像の説明', nil, [100, 100]}}` というような記述）が本文に追加されません。
1. 日記の更新画面の「絵日記（追加）」欄で画像をアップロードする。
2. 「絵日記(一覧・削除)」欄に追加された画像をクリックする。
日記の更新画面を開いたときに「絵日記(一覧・削除)」欄に元々表示されていた画像をクリックしたときには正しく動作します。
画像のアップロードと画像のクリックを続けて行おうとしたときに正しく動作しません。
#545 でjQueryの `live()` の代わりに `on()` を使うように修正が行われています。
しかし、単純に置き換えるだけだと `live()` にあった「後から追加された要素に対してもイベントハンドラを設定する」という機能が有効にならず、その結果上に書いた問題が発生するのだと思います。
https://api.jquery.com/live/#entry-longdesc
にある例のように `on()` にselectorを指定するようにすると `live()` と同じ挙動になるようなので、そのように修正しました。
このPRで修正しているのは `.image-img` というセレクターに対する処理だけです。
#545 ではこれ以外に `#plugin-image-delimage` というセレクターに対する `live()` も `on()` に変更しています。こちらも同様の修正をした方がいいのかもしれませんが、現状で問題が発生するような操作を見つけられなかったのでこちらには手を付けていません。

image.js: 日記更新画面で画像をクリックしたときの動作を修正

---

README.md

Heroku の free plan がなくなるので、お試し目的で Heroku Button を設置するのは不適切になった。
ただし、Heroku での運用そのものは引き続きサポートするため、app.json やプラグインは削除しない。

remove heroku button from README

---

lib/tdiary/rack/auth/omniauth/authorization.rb

Twitter でOAuth しようとすると Location ヘッダが大文字であることで lint エラーが出ました。
https://github.com/tdiary/tdiary-core/pull/1068 の続きかも知れません。
小文字にするとログインできました。

Make cases lower for Location

---

lib/tdiary/dispatcher.rb

Because rack.input is not a StringIO, and doesn't respond to rewind.

Fix for Rackup::Handler::WEBrick in Rack 3

---

.github/workflows/ci.yml

niden/actions-memcached@v7 is not working today
see https://github.com/tdiary/tdiary-core/actions/runs/10515580853/job/29135950931?pr=1171#step:5:4

Use official services context for memcached

---

Gemfile
Gemfile.lock
lib/rack/server.rb

Rackup-2.2.x removed `rack/server`. But we couldn't migrate jasmine 3.x yet.

Workaround for Rackup-2.2

---

index.rb
update.rb

rackup/handler/cgi is removed from rackup.rb at https://github.com/rack/rackup/commit/be545952432d0f03c954c56413a9535212ac71d5

Explicitly load Rackup::Handler::CGI

---

Gemfile

Rack::Session was moved to a separate gem. This change causes omniauth not working.
https://github.com/rack/rack/blob/main/UPGRADE-GUIDE.md

Bump up rack-3.1
