tdiary/tdiary-core

.travis.yml, spec/acceptance/append_comment_spec.rb, spec/acceptance/save_conf_security_spec.rb, spec/acceptance_helper.rb
secure mode を対象としたテスト向けのコードがいくつか残っていたので消しました。テストグリーンを確認したらマージします。
=> Removed secure mode on test

misc/plugin/amazon.rb
see https://github.com/tdiary/tdiary-core/issues/579#issuecomment-231955363
=> amazon.rb に nil 参照するケースが残っていたのでさらなる修正

lib/tdiary/core_ext.rb
http://www.emoji-cheat-sheet.com/graphics/emojis/heart.png
->
http://www.webpagefx.com/tools/emoji-cheat-sheet/graphics/emojis/heart.png
Response for the current URL:
% curl -I http://www.emoji-cheat-sheet.com/graphics/emojis/heart.png
HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Thu, 28 Jul 2016 04:57:40 GMT
Content-Type: text/html; charset=iso-8859-1
Content-Length: 257
Connection: keep-alive
Keep-Alive: timeout=15
Location: http://www.webpagefx.com/tools/emoji-cheat-sheet/
Expires: Thu, 04 Aug 2016 04:57:40 GMT
Cache-Control: max-age=604800
ngpass_ngstatic: 1
Response for the new URL:
% curl -I http://www.webpagefx.com/tools/emoji-cheat-sheet/graphics/emojis/heart.png
HTTP/1.1 200 OK
Date: Thu, 28 Jul 2016 04:57:30 GMT
Content-Type: image/png
Content-Length: 3302
Connection: …
=> Update emoji URL

ChangeLog, lib/tdiary/version.rb, misc/plugin/category-legacy.rb, misc/plugin/category.rb
Reverts tdiary/tdiary-core#593
=> Revert "fix error about here document in category plugins"

ChangeLog, lib/tdiary/version.rb, misc/plugin/category-legacy.rb, misc/plugin/category.rb
ヒアドキュメントの終端文字列と同じ文字列を日記に書き込むことでエラーになるという報告を受けての修正。 see http://tdiary-users.osdn.jp/cgi-bin/wforum/wforum.cgi?mode=allread&no=6793&page=0
* ヒアドキュメントの代わりにString#dumpを利用
* 一部のコードをループの外に出した(最適化)
=> fix error about here document in category plugins

misc/plugin/amp.rb, views/amp.rhtml
* no longer need structured data since Aug 2016
* remove Oga dependency
* search the path of base.css in theme_paths_local
=> amp.rb: refactoring

lib/tdiary/filter/spam.rb, lib/tdiary/plugin/00default.rb, lib/tdiary/plugin/10spamfilter.rb, spec/fixtures/tdiary.conf.gem, spec/fixtures/tdiary.conf.rack, spec/fixtures/tdiary.conf.webrick, tdiary.conf.beginner
CIでエラーが出ているので修正する試み。
手元でもエラーになるが、条件を変えずに実行しても、なぜかエラーの数すら一定しないことがある。filterまわりがおかしい感触。エラーが出るようになったのは最近だが、5.0.0まで遡っても同じエラーが出るので、なにがトリガーになったのかよくわからない。
手元で再現できる人はちょっと追ってみてもらえるとありがたいです。
=> [WIP] try to fix CI error

js/comment_emoji_autocomplete.js, lib/tdiary/core_ext.rb, spec/acceptance/view_comment_spec.rb, spec/core/core_ext_spec.rb
=> use protocol relative URL for emoji

ChangeLog, js/amazon_bitly.js, js/category_autocomplete.js, js/comment_emoji_autocomplete.js, js/highlight.js, js/image.js, js/preview.js, lib/tdiary/plugin/00default.rb, lib/tdiary/version.rb, misc/plugin/category_autocomplete.rb, misc/plugin/comment_emoji_autocomplete.rb, spec/acceptance/save_conf_plugin_spec.rb
jQueryとjQuery UIを最新版にします。jQuery 3.0で削除された(ないしは削除予定の)関数を置き換えるなどの修正も同時に行っています。
=> [WIP] update jQuery to 3.0 and jQuery UI latest

theme/default/default.css
スマホで貼った写真が間延びする件の調整(defaultテーマ)
=> adjust image height on smartphone

misc/paas/heroku/Gemfile.lock
Gemfileが更新されたのでHeroku用のGemfile.lockを追従
=> follow updating Gemfile into Heroku settings

Gemfile, Gemfile.lock, misc/paas/heroku/Gemfile.lock, spec/acceptance_helper.rb, spec/core/plugin_spec.rb
https://github.com/tdiary/tdiary-core/issues/661 をやる前に warning が結構気になったので直しておきます。
=> Remove warnings

Gemfile, Gemfile.lock, tdiary.gemspec
理由はまだ深追いしてませんが Jasmine 3 にすると CI が壊れてしまうので、一旦 2 に固定しようと思います。
=> Lock jasmine2

misc/paas/heroku/Gemfile.lock
=> fix deploy error on heroku by mismatching Gemfile

.travis.yml, Gemfile.lock, lib/tdiary/tasks/release.rake, misc/paas/heroku/Gemfile.local, misc/paas/heroku/Gemfile.lock
* test it on TravisCI
* use it on Heroku
* update bundles
* add depends packages into tarball
=> support ruby 2.6.0

doc/INSTALL-paas.md
#641 に関連して、Sqale のインストールガイドが残っていたので削除しました。
=> Remove document of Sqale because service close

Gemfile.lock, lib/tdiary/plugin.rb, misc/plugin/amp.rb, spec/core/plugin_spec.rb, spec/plugin/plugin_helper.rb
ruby 2.7の非互換によって発生するエラー/警告を消していくPR。
=> Support ruby 2.7.0-preview1

doc/INSTALL-paas.md, misc/paas/heroku/tdiary.conf
* pass options by environment variables
* AMAZON_ACCESS_KEY
* AMAZON_SECRET_KEY
=> use amazon plugin on heroku again

ChangeLog, misc/plugin/amazon.rb
Signed-off-by: Tada, Tadashi <t@tdtds.jp>
=> fix #858: error on amazon plugin without access_key or secret_key

ChangeLog, js/category.js, misc/plugin/category.rb, misc/plugin/en/category.rb, misc/plugin/ja/category.rb
=> Add option to sort reverse the category list, fix #845

Gemfile, Gemfile.lock, misc/paas/heroku/Gemfile.lock
for remove vulnerable rest-client gem
=> update coveralls gem to 0.8.x

misc/plugin/makerss.rb
* remove unnessesary CGI.escape to baseuri
Signed-off-by: Tada, Tadashi <t@tdtds.jp>
=> fix #871 error on makerss plugin

.devcontainer/README.md, .devcontainer/devcontainer.json, .devcontainer/run-app.sh, .devcontainer/setup-app.sh, .dockerignore, .gitignore, .vscode/launch.json, Gemfile, Gemfile.lock, misc/paas/heroku/Gemfile.lock
* add some gems for IDE debugging support
* add some setup scripts
* add settings for vscode
=> Vscode debug

.devcontainer/Dockerfile, .devcontainer/setup-app.sh
* make a user 'vscode' in Docker as UID 1000
* check remote repos by 'ls-remote' sub command
=> use non root user in remote-container

.devcontainer/devcontainer.json, Gemfile, Gemfile.lock, lib/tdiary/io/default.rb
* devcontainer to ruby:3
* use "block_given?" instead of "iterator?"
* add some gems into test: rexml and webrick
=> fix spec error on ruby3

Gemfile.lock, misc/paas/heroku/Gemfile.local, misc/paas/heroku/Gemfile.lock
* update bundled gems
* update ruby to 3.0 on heroku
=> update ruby to 3.0 and bundles

app.json
* add MONGODB_URI to env
* add descriptions to env
=> fix error of heroku button

Dockerfile
=> use ruby 3.0 on Docker

Gemfile, Gemfile.lock, lib/tdiary/dispatcher/index_main.rb
Fixed https://github.com/tdiary/tdiary-core/issues/991
=> Support Ruby 3.1

.devcontainer/devcontainer.json, .devcontainer/setup-app.sh, .vscode/launch.json, .vscode/tasks.json, Gemfile, Gemfile.lock, misc/paas/heroku/Gemfile.local, misc/paas/heroku/Gemfile.lock
* use debug.gem
* add some exetentions into devcontainer
* update ruby to 3.1
=> use ruby 3.1 on heroku

.github/workflows/ci.yml, Gemfile.lock, misc/paas/heroku/Gemfile.local, misc/paas/heroku/Gemfile.lock
* ruby 3.1でspecが通る
* ruby 3.1でbundle update
* CIにruby 3.1を追加
=> support ruby 3.1 and update bundles

README.md
=> Fixed typo in readme and added link

index.rb, update.rb
Followed up https://github.com/tdiary/tdiary-core/pull/1037
=> Use Rackup::Handler instead of Rack::Handler

Gemfile.lock, index.rb, lib/aws/pa_api.rb, lib/tdiary/application.rb, lib/tdiary/dispatcher.rb, lib/tdiary/dispatcher/index_main.rb, lib/tdiary/dispatcher/update_main.rb, lib/tdiary/rack/auth/basic.rb, lib/tdiary/rack/auth/omniauth/authorization.rb, lib/tdiary/rack/valid_request_path.rb, misc/filter/antispamservice.rb, misc/filter/plugin/antispamservice.rb, misc/migrate.rb, misc/plugin/ping.rb, update.rb, views/mail.rtxt
Resolved https://github.com/tdiary/tdiary-core/issues/1050
勢いで上げてしまってご迷惑をおかけしました...。とりあえず `rackup` して日記の表示ができるようにはしました。
=> Rack 3 で動かない箇所を直しました

lib/tdiary/dispatcher/update_main.rb
c2cd87e0a61dd423ac16494281b42c9f208e72b6
=> Typofix with c2cd87e0a61dd423ac16494281b42c9f208e72b6

Gemfile, Gemfile.lock, lib/aws/pa_api.rb, lib/tdiary/application.rb, lib/tdiary/dispatcher.rb, lib/tdiary/dispatcher/index_main.rb, lib/tdiary/dispatcher/update_main.rb, lib/tdiary/rack/auth/basic.rb, lib/tdiary/rack/auth/omniauth/authorization.rb, lib/tdiary/rack/valid_request_path.rb, misc/paas/heroku/Gemfile.lock
https://github.com/tdiary/tdiary-core/issues/1055#issuecomment-1968464711 が Rack 3 対応による変更が影響しているのかわからないので一回全部 revert して試します。
=> Revert Rack 3 support

Gemfile, Gemfile.lock, lib/aws/pa_api.rb, lib/tdiary/application.rb, lib/tdiary/dispatcher.rb, lib/tdiary/dispatcher/index_main.rb, lib/tdiary/dispatcher/update_main.rb, lib/tdiary/rack/auth/basic.rb, lib/tdiary/rack/auth/omniauth/authorization.rb, lib/tdiary/rack/valid_request_path.rb, misc/paas/heroku/Gemfile.lock
Revert "Merge pull request #1135 from tdiary/revert-rack3"
This reverts commit dd60aad4ba89af982e076605f27dabe74293703d, reversing changes made to b98d0747f87eba453f96246c11219c0ba1987ab6.
=> Try rack3 again

.github/workflows/ci.yml
https://github.com/tdiary/tdiary-core/actions/runs/15459240237/job/43580887215?pr=1231
=> Fix CI related with Phantomjs

lib/tdiary/tasks/release.rake, tdiary.gemspec
Update to the minimum version to Ruby 3.1 and add Ruby 3.4 for supported version.
=> Update supported versions
